---
- name: Remote Control Using Ansible
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
   - debug: var=ansible_host
  become: true
  become_method: sudo
  become_user: root
  roles:
   - prepare
   - apache
