version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0 
    steps:  
       - checkout
       - run: mkdir -p workspace
       - run: echo "Hello, world!" > workspace/echo-output
          
       - persist_to_workspace:
           root: workspace
           paths:
             - echo-output           
  say-hello:
    docker:
      - image: circleci/node:13.8.0 
    steps:
       - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace  
       - checkout
       - run: |
           if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
           else
            echo "Nope!"; exit 1
           fi

          #command: "echo Hello, World!"

  # say-world:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #      - checkout
  #      - run:
  #          name: "Say world"
  #          command: "echo Hello, print world new!"          

  # PRINT_ENV_VAR:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: "PRINT var"
  #         command: "echo $ENV_TEST"
        

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - say-hello:
           requires:
             - save_hello_world_output     
      #- PRINT_ENV_VAR
      # - say-hello
      # - say-world:
      #     requires:
      #       - say-hello