version: 2.1

jobs:
  myjob1:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: amazon/aws-cli
      working_directory: /tmp    
      steps:
        - checkout # check out the code in the project directory
        - run:
           name: Install tar utility
           command: |
             yum install -y tar gzip     
             # - run: 
             #name: create directory
             #command: |
             #mkdir ~/temp
             #- run:
             #name: create file
             #command: |
             #touch ~/temp/inventoryX.txt     
        - run:
           name: Create Cloudformation Stack
           command: |
             aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
        - persist_to_workspace:
             root: workspace
             paths:
               - output.txt              
        - run:
           name: copy ip in inventory file
           command: |
             aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> /tmp/workspace/output.txt
        - run:
           name: check ip attached
           command: | 
             cat /tmp/workspace/output.txt 
  configure_infrastructure:
      docker:
       - image: python:3.7-alpine3.11
      steps:      
        - checkout
        - attach_workspace:
            at: /tmp/workspace
        - run: echo /t  mp/workspace/output.txt >> inventory.txt
        - run: cat inventory.txt
        - add_ssh_keys:
             # You can get this ID in the section where you registered the SSH Key
             fingerprints: ["8b:05:b2:00:a7:f2:40:16:3d:eb:c6:d0:5c:1c:df:50"]
      
        - run:
           name: Install Ansible
           command: |
              apk add --update ansible
          # Install Ansible
        - run:
           name: Run Playbook and Configure server
           command: |
             ansible-playbook -i inventory.txt main.yml

workflows:
  myWorkflow:        
    jobs:
      - myjob1
      - configure_infrastructure:
           requires:
            - myjob1
